# Package namespace for the `auto-patcher` NUR.
#
# This is the attrset consumers see through NUR, e.g.
#   nur.repos.auto-patcher.<pkg>_<major>_<minor>
#
# GENERATED by auto-packager by scanning pkgs/. Do NOT edit by hand — add or
# update packages with `auto-packager set` / `sync-all`, or re-derive the file
# from the current pkgs/ tree with `auto-packager regen`. Every entry is a flat
# derivation so the whole set stays buildable and indexable by NUR search.
{ pkgs ? import <nixpkgs> { } }:

{
  auto-packager = pkgs.callPackage ./pkgs/auto-packager { };
  auto-patcher = pkgs.callPackage ./pkgs/auto-patcher { };
}
